# Generated by Django 3.2.8 on 2023-10-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gdp',
            old_name='contry_code',
            new_name='country_code',
        ),
        migrations.RenameField(
            model_name='gdp',
            old_name='gpd',
            new_name='gdp',
        ),
    ]
